**Decision Trees**

**Treinando e visualizando**

In [1]:
from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier

iris = load_iris()
X = iris.data[:, 2:]
y = iris.target

tree_clf = DecisionTreeClassifier(max_depth=2)
tree_clf.fit(X, y)

DecisionTreeClassifier(max_depth=2)

In [2]:
from sklearn.tree import export_graphviz
import graphviz

def graph_plot(model, feature_names, class_names=None):
    dotData = export_graphviz(model,
                              out_file=None,
                              feature_names=feature_names,
                              class_names=class_names,
                              rounded=True,
                              filled=True
        )
    graph = graphviz.Source(dotData)
    graph.view()

In [3]:
graph_plot(tree_clf, iris.feature_names[2:], iris.target_names)

**Estimando a probabilidade das classes**

In [4]:
tree_clf.predict_proba([[5, 1.5]]) #comprimento e largura

array([[0.        , 0.90740741, 0.09259259]])

**0%** para classe 0, setosa.

**90,74%** para classe 1, versicolor.

**9,25%** para classe 2, virginica.

In [5]:
tree_clf.predict([[5, 1.5]])

array([1])

**Usando Árvore de Decisão para regressão**

In [6]:
import numpy as np

np.random.seed(42)
m = 200
X = np.random.rand(m, 1)
y = 4 * (X - 0.5) ** 2
y = y + np.random.randn(m, 1) / 10

In [7]:
from sklearn.tree import DecisionTreeRegressor

tree_reg = DecisionTreeRegressor(max_depth=2)
tree_reg.fit(X, y)

DecisionTreeRegressor(max_depth=2)

In [8]:
graph_plot(tree_reg, ["x1"])

In [14]:
tree_reg.predict([[0.6]])

array([0.11063973])

In [9]:
tree_reg2 = DecisionTreeRegressor(max_depth=3)
tree_reg2.fit(X, y)

DecisionTreeRegressor(max_depth=3)

In [10]:
graph_plot(tree_reg2, ["x1"])

In [13]:
tree_reg2.predict([[0.6]])

array([0.08445536])

In [11]:
tree_reg3 = DecisionTreeRegressor(min_samples_leaf=10)
tree_reg3.fit(X, y)

DecisionTreeRegressor(min_samples_leaf=10)

In [12]:
tree_reg3.predict([[0.6]])

array([0.02780903])